# -*- coding: utf-8 -*-
"""01_Time_Converter.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYN5ElzhojWJ-w9Z7yW-tRMhM-oIUED7
"""

minutes = int(input("Enter minutes: "))

hours = minutes // 60
remaining_minutes = minutes % 60

print(hours, "hrs", remaining_minutes, "minutes")

