# -*- coding: utf-8 -*-
"""02_Remove_Duplicates.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYN5ElzhojWJ-w9Z7yW-tRMhM-oIUED7
"""

text = input("Enter string: ")

result = ""

for char in text:
    if char not in result:
        result += char

print("Result:", result)

